name: Research on Ryugakusei
favicon: null
layout_spectrum: 0.75384
typography_spectrum: 0.74279
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#b4b4b4'
    - '#616161'
    - '#414141'
    - '#0d0d0d'
  brandStrength: 0.601607185555622
  lightness: 0.963434984209016
  saturation: 0.7125278383027762
  rhythmicContrast: 0.08024034881964326
purpose: []
